### ISSUE TITLE
Can't access plist file in UITests folder

### ISSUE THREAD

**Issue by kristiyandobrev** [Reedyuk/set-xcode-plist-value#1]
I am trying to access the `Info.plist` file in `UITests` folder of my project by giving the path to it:

`MyProjectUITests/Info.plist`

But `Bitrise` throws the following error: 

` [!] File doesn't exist at specified Info.plist path: MyProjectUITests/Info.plist
`

Though I can verify that the file exists and it's exactly in that folder.

The only solution I tried so far is to provide the path to the plist file like: 

`./MyProjectUITests/Info.plist`

..which threw the same error as above.

**Comment by Reedyuk** [comment]
Hi Kristi,
Have a look in your bitrise log for "Provided Info.plist" and there should be a path like you specified. Here is what mine looks like:
(i) Provided Info.plist path: ProjectFolder/Supporting Files/Info.plist
(i) Plist Key: some_plist_key
(i) Plist value: new_plist_value

In my case, i put my info.plist file in the Supporting Files folder, but that shouldnt matter. I have a feeling that its something related to the location you are specifying for the plist file. Remember its case sensitive.

**Comment by Reedyuk** [comment]
Hi Kristi,
I have just tested locally the script to change a value in the test folders plist file and it worked.
Here is a gist.
https://gist.github.com/Reedyuk/84d7aa435a39a187ae8965eb7891de25
I would suggest that the location for the plist file must be incorrect.

**Comment by kristiyandobrev** [comment]
Hi ! You are totally right @Reedyuk, the issue was with the location. Though I think it's worth mentioning somewhere in the docs that if we are aiming for a file different then the main project's `Info.plist` (e.g my case), we should probably use the `$BITRISE_SOURCE_DIR` envVar as a prefix.
